# Generated by Django 4.2.8 on 2024-02-01 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data_analysis', '0002_alter_dailypricemodel_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypricemodel',
            name='indexes',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_data_analysis.indexmodel'),
        ),
    ]
