# Generated by Django 4.2.8 on 2024-02-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data_analysis', '0003_alter_dailypricemodel_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypricemodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailypricemodel',
            name='indexes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_data_analysis.indexmodel'),
        ),
    ]
